### ISSUE TITLE
SI Sextupole Model07 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/si-sextupoles-s15#1]
Sextupole:
 si-sextupoles-s15/model-07/simulation/magnetic/2017-02-24_SI_Sextupole_Model07_Sim_X=-14_14mm_Z=-500_500mm_Imc=158.48A.txt 

Sextupole + QS:
 si-sextupoles-s15/model-07/simulation/magnetic/2017-02-24_SI_Sextupole_Model07_Sim_QS_X=-14_14mm_Z=-500_500mm_Imc=158.48A_Iqs=4.3A.txt 

Sextupole + CV:
 si-sextupoles-s15/model-07/simulation/magnetic/2017-02-24_SI_Sextupole_Model07_Sim_CH_CV_X=-14_14mm_Z=-500_500mm_Imc=158.48A_Ich=0A_Icv=10A.txt 

Sextupole + CH:
 si-sextupoles-s15/model-07/simulation/magnetic/2017-02-24_SI_Sextupole_Model07_Sim_CH_CV_X=-14_14mm_Z=-500_500mm_Imc=158.48A_Ich=10A_Icv=0A.txt 

Sextupole + CH + CV:
 si-sextupoles-s15/model-07/simulation/magnetic/2017-02-24_SI_Sextupole_Model07_Sim_CH_CV_X=-14_14mm_Z=-500_500mm_Imc=158.48A_Ich=10A_Icv=10A.txt

**Comment by xresende** [comment]
fmaps of SX, SX+CH, SX+CV and SX+QS analysed. all integrated main multipoles achieved (with QS slightly bellow spec,  ~0.1%,  but acceptable)

DA calculations running at this point.

**Comment by xresende** [comment]
DA calculations finished. No deterioration of DA or beam lifetime. Models 07 approved.
